stages:
  - test
  - build
  - deploy

realizar_testes:
  stage: test
  image: node:20.7.0-alpine3.17
  before_script:
    - cd app/
    - npm install
  script:
    - npm test
  artifacts:
    when: always
    reports:
        junit: app/junit.xml
  
build_images:
  stage: build
  needs:
    - realizar_testes
  image: docker:latest
  services:
    - docker:dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  
  script:
    - docker build -t gitlab-cicd-node .
    - docker tag gitlab-cicd-node jadson.sousamattos/gitlab-cicd-node:1.0
    - docker push jadson.sousamattos/gitlab-cicd-node:1.0

deploy_dev:
  stage: deploy
  image: docker:latest
  services: docker:dind
  needs:
    - build_images
  tags:
    - gcp
  script:
    - docker run -d --name nodeapp -p 3000:3000 jadson.sousamattos/gitlab-cicd-node:1.0